### ISSUE TITLE
Resolution issue 

### ISSUE THREAD

**Issue by Swompen** [doritohead/InstagramApp-QB-Phone#2]
![image](https://user-images.githubusercontent.com/16113909/213035295-a2a719e6-8264-405f-9864-55001fa73822.png)
Got this issue, I'm running window mode 1920x1080 currently and I saw that it's using the basic CSS for all these buttons.
what changes have you made to your default CSS to make it work that well?

**Comment by doritohead** [comment]
Hello, so inside your phone.css you want to find the ```phone-menu-cancel``` and replace the buttons with this
```.phone-menu-cancel{
    background:#d46215;
    margin-left: 15%;
    padding: 4.0%;
}
.phone-menu-cancel:hover{
    background: #c27e47;
}

.phone-menu-delete{
    background:#b91111;
    margin-left: 5%;
    padding: 4.0%;
}
.phone-menu-delete:hover{
    background: #c27e47;
}

.phone-menu-camera{
    background:#37be0e;
    margin-left: 5%;
    padding: 4.0%;
}
.phone-menu-camera:hover{
    background: #6cac59;
}

.phone-menu-accept{
    background:#90e278;
    margin-left: 5%;
    padding: 4.0%;
}
.phone-menu-accept:hover{
    background: #6cac59;
}```
